### ISSUE TITLE
[BUG] [1.19] Barrel blocks are opaque

### ISSUE THREAD

**Issue by jamesjimmy88** [NovaMachina/ExNihiloSequentia#381]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Barrels are considered opaque blocks, meaning that placing a barrel on grass/mycelium will eventually convert it to dirt, making the creation of Witch Water much harder.

### Expected Behavior

I'd expect for the mycelium below the barrels to not die

### Steps to Reproduce

Just place a barrel above a Grass or Mycelium block and wait a bit

### Minecraft Version

1.19.X

### Forge Version

43.1.52

### Ex Nihilo: Sequentia Version

4.0.0.49-beta

### Log File

Not needed for the issue

**Comment by NovaMachina** [comment]
Fixed in latest version

**Comment by sasaavirus** [comment]
updated to ExNihiloSequentia-1.19.2-4.1.0.53-beta.jar and sadly still happens
